server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vacation_tracker?stringtype=unspecified
    username: postgres
    password: nesa1995
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    hibernate:
      ddl-auto: update
    show-sql: false

security:
  key: somerandomkeywhichislongenoughtoalignwiththejwtspecification
